project:
  type: website
  output-dir: docs

website:
  title: "Akash Ansari"
  page-footer:
    left: 
      - icon: github
        href: https://github.com/Akash-Ansari
      - icon: linkedin
        href: https://www.linkedin.com/in/akashansari/
    right: "Copyright 2023, Akash Ansari"
    border: false
    background: light
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/Akash-Ansari
      - icon: twitter
        href: https://twitter.com/Akash_Ansari1
    collapse-below: sm
    search: true
format:
  html:
    theme: 
      - customized_styles.scss
    mainfont: Montserrat
    toc: true

editor: visual

